version: '2'
services:
  sphinx:
    image: leodido/sphinxsearch:2.1.9
    volumes:
        - "./.data/sphinx/conf:/usr/local/etc"
        - "./.data/sphinx/data:/var/lib/sphinx/source"
    ports:
        - "9307:9307"