demoApp:
  image: jdocker/app
  links:
    - myslqdb
  ports:
    - "8080:8080"
  volumes:
    - ./app:/app
myslqdb: # или через консоль: docker run --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 -e MYSQL_USER=dev -e MYSQL_PASSWORD=123456 -e MYSQL_DATABASE=myapp -d mysql:5.7
  image: mysql:5.7
  ports:
    - "3306:3306"
  volumes:
        - "./.data/db:/var/lib/mysql"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: iozol
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: test
#sphinx:
#    image: centurylink/sphinx:2.1.9.01
#    volumes:
#        - $PWD:/usr/local/etc
#    ports:
#        - "9306:9306"