  sphinx:
    image: leodido/sphinxsearch:2.1.9
    command: ./bin/searchd.sh

    volumes:
      - ./sphinx/
      - ./sphinx/sphinx.conf:/usr/local/etc/sphinx.conf
      - ./sphinx/rotate-all.sh:/usr/local/etc/rotate-all.sh
      - ./sphinx:/var/lib/sphinx/source/

      - ./.data/sphinx/data/diz:/var/diz/sphinx
      - ./.data/sphinx/data/run:/var/run/sphinx
      - ./.data/sphinx/data/lib:/var/lib/sphinx
      - ./.data/sphinx/data/log:/var/log/sphinx
      - ./.data/sphinx/data/idx:/var/idx/sphinx
    ports:
        - "9307:9307"