  sphinx:
    image: leodido/sphinxsearch:2.2.9
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    #command: /bin/sh
    #command: ./bin/searchd.sh
    #command: /usr/local/etc/rotate-all.sh

    volumes:
      - ./sphinx/sphinx.conf:/usr/local/etc/sphinx.conf
      - ./sphinx/rotate-all.sh:/usr/local/etc/rotate-all.sh
      - ./sphinx:/var/lib/sphinx/source/
      - ./sphinx:/var/lib/sphinx/

      - ./.data/sphinx/data/diz:/var/diz/sphinx
      - ./.data/sphinx/data/run:/var/run/sphinx
      - ./.data/sphinx/data/lib:/var/lib/sphinx
      - ./.data/sphinx/data/log:/var/log/sphinx
      - ./.data/sphinx/data/idx:/var/idx/sphinx
    ports:
        - "9307:9307"

        apt-get update
        apt-get install software-properties-common
        apt-get install python3-software-properties
        apt-get install python-software-properties

        add-apt-repository ppa:builds/sphinxsearch-rel22
        apt-get update
        apt-get install sphinxsearch



docker run --name sphinx -d sem/sphinxsearch

        docker run --name sphinx -d \
          --net sphinx_net \
          -v /host/to/path/data:/var/lib/sphinxsearch/data
          -e "SPHINX_MODE=indexing" \
          -e "SPHINX_CONF=/etc/sphinxsearch/sphinx_pgsql.conf" \
          romeoz/docker-sphinxsearch