version: '2'
services:
  # docker run -p 176.112.222.8:8080:8080 --link mysql:mysql jdocker/app
  demoApp:
      image: jdocker/app
      net: sem_net
      depends_on:
        - myslqdb
  #    links:
  #      - myslqdb
      net: sem_net
      ports:
        - "8080:8080"
        - "8000:8000"
      volumes:
        # HOST_DIR:CONTAINER_DIR
        - ./app:/app
      environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://myslqdb/test?autoReconnect=true&useSSL=false # mysql_host = myslqdb !!!
          SPRING_DATASOURCE_USERNAME: iozol
          SPRING_DATASOURCE_PASSWORD: 123456

  # docker run --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 -e MYSQL_USER=iozol -e MYSQL_PASSWORD=123456 -e MYSQL_DATABASE=test -d mysql:5.7
  myslqdb:
      image: mysql:5.7
      container_name: sem_mysql
      net: sem_net
      restart: always
      ports:
        - "3306:3306"
      volumes:
        # смонтировать /var/lib/mysql контейнера на ./.data/db докер хоста
        # ./.data/db - путь к данным относительно текущей папки, где запускается docker-compose up
        # /var/lib/mysql - путь в контейнере myslqdb
        - "./.data/db:/var/lib/mysql" # ./.data/db - путь к данным относительно текущей папки, где запускается docker-compose up
      environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_USER: iozol
          MYSQL_PASSWORD: 123456
          MYSQL_DATABASE: test

  sphinx:
      image: sphinx2
      container_name: sem_sphinx
      net: sem_net
      restart: always
      ports:
         - "9307:9307"

  config:
      environment:
        #CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      image: config-service/src/main/docker
      container_name: config_service
      net: sem_net
      restart: always
      logging:
        options:
          max-size: "10m"
          max-file: "10"

  registry:
      environment:
        #CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      image: registry-service/src/main/docker
      container_name: registry-service
      net: sem_net
      restart: always
      ports:
        - 8761:8761
      logging:
        options:
          max-size: "10m"
          max-file: "10"
