spring:
  cloud:
    config:
      server:
        git:
#          uri: C:\\1\\test
#          uri: C:\\Users\\ozol\\Desktop\\delete\\sem-config
          uri: https://github.com/dj-kefir/sem-config
          username: dj-kefir
          password: glamovga1961l2
server:
    port: 8888
logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.cloud.config.server: DEBUG

# http://10.0.7.16:8888/test-service/development
# http://10.0.7.16:8888/test-service/production